---
title: "individual1"
author: "cyber-atlas"
date: "April 11, 2019"
output: html_document
---

```{r}
# library('ggplot2')
# library('dplyr')
library('tidyverse')
library('maps')

acc<- read.csv('accident.csv', stringsAsFactors = FALSE)
# acc <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/accident.csv", stringsAsFactors = FALSE)
# person <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/person.csv")
person <- read.csv('person.csv', stringsAsFactors = FALSE)
 
# names(acc)
# person$PER_TYP
# names(person)

```

Assuming the first day of the week is Sunday in this case


```{r}

class(acc$DAY_WEEK)

acc$DAY_WEEK <- factor(acc[,'DAY_WEEK'])
levels(acc$DAY_WEEK) <- list("Sunday" = 1, 'Monday'=2, 'Tuesday'=3, 'Wednesday'=4, 'Thursday'=5, 'Friday'=6, 'Saturday'=7)

levels(acc$DAY_WEEK)

ggplot(data=acc, aes(x=DAY_WEEK, color= DAY_WEEK, fill=stat(count)))+
  geom_bar()+
  #geom_bar(aes(y=stat(count)))+
  geom_text(stat='count', aes(label=..count..), vjust = -.5)+
  scale_y_continuous(limits=c(0,6500))+
  theme(axis.text.x = element_text(angle =45, hjust=1))


```

What time of day do accidents most commonly occur

```{r}
class(acc$HOUR)

acc$HOUR<- factor(acc[,'HOUR'])

levels(acc$HOUR)[levels(acc$HOUR) == 99] <- "unknown"

levels(acc$HOUR)

ggplot(data=acc, aes(x=HOUR, fill= stat(count)))+
         #fill=stat(count)))+
  geom_bar()+
  #geom_bar(aes(y=stat(count)))+
  geom_text(stat='count', aes(label=..count..), angle=90,hjust = -.5)+
  scale_y_continuous(limits=c(0,2500))+
  theme(axis.text.x = element_text(angle =75, hjust=1))

```

```{r}

class(acc$DRUNK_DR)

acc$DRUNK_DR<- factor(acc[,'DRUNK_DR'])

#levels(acc$DAY_WEEK) <- list("Sunday" = 1, 'Monday'=2, 'Tuesday'=3, 'Wednesday'=4, 'Thursday'=5, 'Friday'=6, 'Saturday'=7)

levels(acc$'DRUNK_DR')

ggplot(data=acc, aes(x=DRUNK_DR, color=DRUNK_DR))+
         #fill=stat(count)))+
  geom_bar()+
 # geom_bar(aes(y=frequency(DRUNK_DR)))+
  geom_text(stat='count', aes(label=..count..), angle=0,vjust = -.1)
  #scale_y_continuous(limits=c(0,3000))
  #theme(axis.text.x = element_text(angle =75, hjust=1))
  #facet_wrap(~DRUNK_DR)


```

Part 2

Identify the drivers


```{r}
#Drivers are person type 1, so only select those
drivers <- person %>% filter(PER_TYP == 1)

driversAccByCase <- inner_join(drivers, acc, by = "ST_CASE")

head(driversAccByCase)


ggplot(driversAccByCase, aes(x=factor(HOUR.y), fill=factor(SEX)))+
  geom_bar()+
  facet_wrap(~DAY_WEEK)+
  theme(axis.text.x = element_text(angle =75, hjust=1, size= 8))
  # geom_text(stat='count', aes(label=..count..), angle=90,hjust = -.5)

```


Plot choropleth map of accidents ona county level
```{r}
#Import the frpp data telling us state code info
frpp <- readxl::read_xlsx('FRPP GLC United States.xlsx')
#copy acc in case we need it again
acc2 <- acc
#Need to save as a df first I guess
frpp<-data.frame(frpp)
class(frpp)
colnames(frpp) <- frpp[1,]
frpp <- frpp[-1, ]
 head(frpp)
countyPlottingInfo <- map_data("county")

names(frpp)[6] = "COUNTY"
names(frpp)[7] = "County_Name"
frpp$COUNTY = factor(frpp$COUNTY)
acc2$COUNTY = factor(acc2$COUNTY)
names(countyPlottingInfo)[6] = "County_Name"

countacc = inner_join(acc2,frpp, by="COUNTY") %>% select(LATITUDE,LONGITUD,COUNTY,"County_Name",DAY,MONTH,YEAR,HOUR,"State Name")

countacc = countacc %>% 
  mutate(County_Name = tolower(County_Name))
countaccgroup = countacc %>% group_by(County_Name) %>% summarise(total_crashes = n())

head(countaccgroup)
head(countyPlottingInfo)

countaccgroup = left_join(countaccgroup,countyPlottingInfo, by="County_Name")

# countaccgroup %>% group_by("County_Name") %>% ggplot(aes(x = long.x, y = lat.x, fill=total_crashes)) + geom_polygon(aes(group=group.x))   + guides(fill=guide_legend("Total Crashes"))
countaccgroup %>% group_by("County_Name") %>% ggplot(aes(x = long, y = lat, fill=total_crashes)) + geom_polygon(aes(group=group))   + guides(fill=guide_legend("Total Crashes"))


```


```{r}

states <- map_data("state")
accBySzn <- countacc %>% 
  group_by(County_Name,MONTH) %>% 
  summarise(total_crashes=n())

accBySzn <- transform(accBySzn, SEASON = case_when((accBySzn$MONTH >= 11 | accBySzn$MONTH <= 3) ~ "WINTER", (accBySzn$MONTH >= 5 & accBySzn$MONTH <= 8) ~ "SUMMER"))

accBySzn = accBySzn[complete.cases(accBySzn[,4]),]
accBySzn = accBySzn %>% group_by(County_Name,SEASON) %>% summarise(total_crash = sum(total_crashes))  
accBySzn = accBySzn %>% left_join(counties,by="County_Name")
accBySzn = accBySzn %>% group_by(region,SEASON) %>% summarise(total_crashes=sum(total_crash))
accBySzn = accBySzn %>% spread(SEASON,total_crashes)

accBySzn = accBySzn %>% group_by(region) %>% summarise(ratioSUMbyWINT = SUMMER/WINTER)
accBySzn = accBySzn %>% left_join(states,by="region")
# accBySzn %>% group_by("region")
ggplot(accBySzn, aes(x = long, y = lat,fill=ratioSUMbyWINT)) + 
  geom_polygon(aes(group=group)) +
  guides(fill=guide_legend("Crash Percentage")) +
  scale_fill_continuous(low="green",high = ("black"))

```

Becasuse the low of the Crash percentage is less than 1 but positive. Most of the crashes happen in winter. 

